apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: haproxy
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "{{ .Release.Name }}.{{ .Values.base_url }}"
    http:
      paths:
      - path: /
        backend:
           serviceName: balancer
           servicePort: 80
      - path: /stats
        backend:
           serviceName: balancer
           servicePort: 90

