apiVersion: v1
kind: Service
metadata:
  name: balancer
  labels:
     app: balancer
spec:
  type: ClusterIP
  selector: 
     app: balancer
  ports:
    - name: application
      port: 8080
      targetPort: 80
      protocol: TCP
    - name: app-stats
      port: 90
      targetPort: 90
      protocol: TCP
